// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: Date.now,
      _7: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _8: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _9: () => new Error().stack,
      _10: () => typeof dartUseDateNowForTicks !== "undefined",
      _11: () => 1000 * performance.now(),
      _12: () => Date.now(),
      _13: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _14: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _18: (exn) => exn.toString(),
      _19: (exn) => exn.stack,
      _20: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _33: s => JSON.stringify(s),
      _34: s => printToConsole(s),
      _35: o => {
        if (o === null || o === undefined) return 0;
        if (typeof(o) === 'string') return 1;
        return 2;
      },
      _36: (o, p, r) => o.replaceAll(p, () => r),
      _37: (o, p, r) => o.replace(p, () => r),
      _38: Function.prototype.call.bind(String.prototype.toLowerCase),
      _39: s => s.toUpperCase(),
      _40: s => s.trim(),
      _43: (string, times) => string.repeat(times),
      _44: Function.prototype.call.bind(String.prototype.indexOf),
      _45: (s, p, i) => s.lastIndexOf(p, i),
      _46: (string, token) => string.split(token),
      _47: Object.is,
      _51: (o, c) => o instanceof c,
      _83: x0 => new Array(x0),
      _85: x0 => x0.length,
      _87: (x0,x1) => x0[x1],
      _88: (x0,x1,x2) => { x0[x1] = x2 },
      _92: (x0,x1,x2) => new DataView(x0,x1,x2),
      _94: x0 => new Int8Array(x0),
      _95: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _96: x0 => new Uint8Array(x0),
      _98: x0 => new Uint8ClampedArray(x0),
      _100: x0 => new Int16Array(x0),
      _102: x0 => new Uint16Array(x0),
      _104: x0 => new Int32Array(x0),
      _106: x0 => new Uint32Array(x0),
      _108: x0 => new Float32Array(x0),
      _110: x0 => new Float64Array(x0),
      _135: x0 => x0.random(),
      _138: () => globalThis.Math,
      _151: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _152: (handle) => clearTimeout(handle),
      _155: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _157: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _158: (x0,x1) => x0.exec(x1),
      _159: (x0,x1) => x0.test(x1),
      _160: x0 => x0.pop(),
      _162: o => o === undefined,
      _164: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _167: o => o instanceof RegExp,
      _168: (l, r) => l === r,
      _169: o => o,
      _170: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'number') return 1;
        return 2;
      },
      _171: o => o,
      _172: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'boolean') return 1;
        return 2;
      },
      _173: o => o,
      _174: b => !!b,
      _175: o => o.length,
      _177: (o, i) => o[i],
      _178: f => f.dartFunction,
      _179: () => ({}),
      _180: () => [],
      _182: () => globalThis,
      _185: (o, p) => o[p],
      _186: (o, p, v) => o[p] = v,
      _187: (o, m, a) => o[m].apply(o, a),
      _189: o => String(o),
      _190: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._192(f,arguments.length,x0,x1) }),
      _193: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _194: o => [o],
      _195: (o0, o1) => [o0, o1],
      _196: (o0, o1, o2) => [o0, o1, o2],
      _197: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _198: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _199: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _200: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _202: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _204: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _208: x0 => new ArrayBuffer(x0),
      _211: x0 => x0.index,
      _213: x0 => x0.flags,
      _214: x0 => x0.multiline,
      _215: x0 => x0.ignoreCase,
      _216: x0 => x0.unicode,
      _217: x0 => x0.dotAll,
      _218: (x0,x1) => { x0.lastIndex = x1 },
      _219: (o, p) => p in o,
      _220: (o, p) => o[p],
      _229: (x0,x1) => x0.createElement(x1),
      _231: (x0,x1) => x0.querySelector(x1),
      _232: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._232(f,arguments.length,x0) }),
      _233: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._233(f,arguments.length,x0) }),
      _234: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _235: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _236: x0 => x0.preventDefault(),
      _241: () => new AbortController(),
      _242: x0 => x0.abort(),
      _243: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _244: (x0,x1) => globalThis.fetch(x0,x1),
      _245: (x0,x1) => x0.get(x1),
      _246: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._246(f,arguments.length,x0,x1,x2) }),
      _247: (x0,x1) => x0.forEach(x1),
      _248: x0 => x0.getReader(),
      _249: x0 => x0.cancel(),
      _250: x0 => x0.read(),
      _251: x0 => x0.load(),
      _252: (x0,x1) => x0.canPlayType(x1),
      _253: (x0,x1) => x0.cloneNode(x1),
      _254: x0 => x0.pause(),
      _255: x0 => x0.play(),
      _256: x0 => x0.createGain(),
      _257: (x0,x1) => x0.connect(x1),
      _258: (x0,x1,x2) => x0.setValueAtTime(x1,x2),
      _259: () => new AudioContext(),
      _260: (x0,x1) => x0.decodeAudioData(x1),
      _262: x0 => x0.createBufferSource(),
      _263: (x0,x1,x2) => x0.start(x1,x2),
      _264: (x0,x1,x2,x3) => x0.start(x1,x2,x3),
      _267: (x0,x1,x2) => ({event_category: x0,event_label: x1,value: x2}),
      _268: x0 => new Blob(x0),
      _269: (x0,x1) => x0.createImageBitmap(x1),
      _270: (x0,x1,x2,x3,x4) => x0.clearRect(x1,x2,x3,x4),
      _271: (x0,x1,x2,x3,x4) => x0.fillRect(x1,x2,x3,x4),
      _272: (x0,x1,x2,x3,x4,x5,x6) => x0.setTransform(x1,x2,x3,x4,x5,x6),
      _274: (x0,x1,x2,x3,x4) => x0.rect(x1,x2,x3,x4),
      _275: x0 => x0.getBoundingClientRect(),
      _276: x0 => x0.focus(),
      _277: (x0,x1) => x0.item(x1),
      _278: (x0,x1,x2) => x0.uniform1i(x1,x2),
      _283: x0 => x0.save(),
      _284: x0 => x0.clip(),
      _285: x0 => x0.restore(),
      _286: (x0,x1) => x0.append(x1),
      _287: x0 => x0.remove(),
      _288: (x0,x1) => x0.measureText(x1),
      _289: x0 => x0.beginPath(),
      _290: (x0,x1,x2,x3) => x0.strokeText(x1,x2,x3),
      _291: (x0,x1,x2,x3) => x0.fillText(x1,x2,x3),
      _292: (x0,x1,x2) => x0.moveTo(x1,x2),
      _293: (x0,x1,x2) => x0.lineTo(x1,x2),
      _298: (x0,x1) => x0.appendChild(x1),
      _301: x0 => x0.closePath(),
      _309: x0 => x0.fill(),
      _310: (x0,x1,x2,x3,x4,x5,x6) => x0.transform(x1,x2,x3,x4,x5,x6),
      _313: (x0,x1,x2) => x0.blendFunc(x1,x2),
      _314: (x0,x1) => x0.blendEquation(x1),
      _316: x0 => x0.createBuffer(),
      _317: (x0,x1,x2) => x0.bindBuffer(x1,x2),
      _318: (x0,x1,x2,x3) => x0.bufferData(x1,x2,x3),
      _319: (x0,x1,x2,x3) => x0.bufferSubData(x1,x2,x3),
      _320: (x0,x1,x2,x3,x4,x5,x6) => x0.vertexAttribPointer(x1,x2,x3,x4,x5,x6),
      _321: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => x0.drawImage(x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _322: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      _323: (x0,x1) => x0.enable(x1),
      _324: (x0,x1) => x0.disable(x1),
      _325: (x0,x1,x2) => x0.pixelStorei(x1,x2),
      _327: (x0,x1,x2) => x0.bindFramebuffer(x1,x2),
      _328: (x0,x1,x2,x3,x4) => x0.viewport(x1,x2,x3,x4),
      _329: (x0,x1,x2,x3,x4) => x0.colorMask(x1,x2,x3,x4),
      _330: (x0,x1,x2,x3,x4) => x0.clearColor(x1,x2,x3,x4),
      _331: (x0,x1) => x0.clear(x1),
      _333: (x0,x1,x2,x3) => x0.stencilFunc(x1,x2,x3),
      _334: (x0,x1) => x0.activeTexture(x1),
      _335: (x0,x1,x2) => x0.bindTexture(x1,x2),
      _338: x0 => x0.createFramebuffer(),
      _339: (x0,x1,x2,x3,x4,x5) => x0.framebufferTexture2D(x1,x2,x3,x4,x5),
      _340: (x0,x1,x2,x3,x4) => x0.framebufferRenderbuffer(x1,x2,x3,x4),
      _341: (x0,x1,x2,x3) => x0.uniformMatrix4fv(x1,x2,x3),
      _342: (x0,x1) => x0.useProgram(x1),
      _343: (x0,x1,x2,x3,x4) => x0.drawElements(x1,x2,x3,x4),
      _344: x0 => x0.createProgram(),
      _345: (x0,x1,x2) => x0.attachShader(x1,x2),
      _346: (x0,x1) => x0.linkProgram(x1),
      _347: (x0,x1,x2) => x0.getProgramParameter(x1,x2),
      _348: x0 => x0.isContextLost(),
      _349: (x0,x1) => x0.getProgramInfoLog(x1),
      _350: (x0,x1) => x0.createShader(x1),
      _351: (x0,x1,x2) => x0.shaderSource(x1,x2),
      _352: (x0,x1) => x0.compileShader(x1),
      _353: (x0,x1,x2) => x0.getShaderParameter(x1,x2),
      _354: (x0,x1) => x0.getShaderInfoLog(x1),
      _355: (x0,x1,x2) => x0.getActiveAttrib(x1,x2),
      _356: (x0,x1,x2) => x0.getAttribLocation(x1,x2),
      _357: (x0,x1) => x0.enableVertexAttribArray(x1),
      _358: (x0,x1,x2) => x0.getActiveUniform(x1,x2),
      _359: (x0,x1,x2) => x0.getUniformLocation(x1,x2),
      _361: (x0,x1,x2,x3,x4) => x0.renderbufferStorage(x1,x2,x3,x4),
      _362: x0 => x0.createRenderbuffer(),
      _363: (x0,x1,x2) => x0.bindRenderbuffer(x1,x2),
      _364: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _365: (x0,x1,x2,x3) => x0.texParameteri(x1,x2,x3),
      _368: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => x0.texImage2D(x1,x2,x3,x4,x5,x6,x7,x8),
      _369: (x0,x1) => x0.isEnabled(x1),
      _370: (x0,x1,x2,x3,x4,x5,x6) => x0.texImage2D(x1,x2,x3,x4,x5,x6),
      _371: x0 => x0.createTexture(),
      _372: x0 => x0.getError(),
      _376: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._376(f,arguments.length,x0) }),
      _377: (x0,x1) => x0.requestAnimationFrame(x1),
      _378: x0 => new TouchEvent(x0),
      _379: x0 => x0.clear(),
      _381: (x0,x1,x2) => x0.setItem(x1,x2),
      _382: (x0,x1) => x0.getItem(x1),
      _383: (x0,x1) => x0.assign(x1),
      _384: (x0,x1) => x0.replace(x1),
      _385: x0 => x0.reload(),
      _386: (x0,x1,x2) => globalThis.gtag(x0,x1,x2),
      _387: (x0,x1) => x0.error(x1),
      _388: x0 => x0.now(),
      _389: (x0,x1,x2,x3) => ({event_category: x0,event_label: x1,value: x2,name: x3}),
      _394: o => o instanceof Array,
      _404: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _405: a => a.length,
      _407: (a, i) => a[i],
      _408: (a, i, v) => a[i] = v,
      _410: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof ArrayBuffer) return 1;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 2;
        }
        return 3;
      },
      _413: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint8Array) return 1;
        return 2;
      },
      _414: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _415: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int8Array) return 1;
        return 2;
      },
      _416: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _417: o => o instanceof Uint8ClampedArray,
      _418: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _419: o => o instanceof Uint16Array,
      _420: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _421: o => o instanceof Int16Array,
      _422: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _423: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint32Array) return 1;
        return 2;
      },
      _424: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _425: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int32Array) return 1;
        return 2;
      },
      _426: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _429: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float32Array) return 1;
        return 2;
      },
      _430: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _431: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float64Array) return 1;
        return 2;
      },
      _432: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _433: (t, s) => t.set(s),
      _435: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _437: o => o.buffer,
      _438: o => o.byteOffset,
      _439: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _440: (b, o) => new DataView(b, o),
      _441: (b, o, l) => new DataView(b, o, l),
      _442: Function.prototype.call.bind(DataView.prototype.getUint8),
      _443: Function.prototype.call.bind(DataView.prototype.setUint8),
      _444: Function.prototype.call.bind(DataView.prototype.getInt8),
      _445: Function.prototype.call.bind(DataView.prototype.setInt8),
      _446: Function.prototype.call.bind(DataView.prototype.getUint16),
      _447: Function.prototype.call.bind(DataView.prototype.setUint16),
      _448: Function.prototype.call.bind(DataView.prototype.getInt16),
      _449: Function.prototype.call.bind(DataView.prototype.setInt16),
      _450: Function.prototype.call.bind(DataView.prototype.getUint32),
      _451: Function.prototype.call.bind(DataView.prototype.setUint32),
      _452: Function.prototype.call.bind(DataView.prototype.getInt32),
      _453: Function.prototype.call.bind(DataView.prototype.setInt32),
      _458: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _459: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _460: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _461: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _462: Function.prototype.call.bind(Number.prototype.toString),
      _463: Function.prototype.call.bind(BigInt.prototype.toString),
      _464: Function.prototype.call.bind(Number.prototype.toString),
      _465: (d, digits) => d.toFixed(digits),
      _471: (x0,x1) => x0.getContext(x1),
      _474: (x0,x1,x2) => x0.getContext(x1,x2),
      _598: x0 => x0.offsetTop,
      _602: x0 => x0.style,
      _804: x0 => x0.tabIndex,
      _805: (x0,x1) => { x0.tabIndex = x1 },
      _1033: x0 => x0.src,
      _1034: (x0,x1) => { x0.src = x1 },
      _1045: x0 => x0.width,
      _1047: x0 => x0.height,
      _1204: x0 => x0.error,
      _1205: x0 => x0.src,
      _1206: (x0,x1) => { x0.src = x1 },
      _1214: (x0,x1) => { x0.preload = x1 },
      _1216: x0 => x0.readyState,
      _1218: x0 => x0.currentTime,
      _1219: (x0,x1) => { x0.currentTime = x1 },
      _1238: (x0,x1) => { x0.volume = x1 },
      _1880: x0 => x0.width,
      _1881: (x0,x1) => { x0.width = x1 },
      _1882: x0 => x0.height,
      _1883: (x0,x1) => { x0.height = x1 },
      _1916: (x0,x1) => { x0.globalAlpha = x1 },
      _1918: (x0,x1) => { x0.globalCompositeOperation = x1 },
      _1924: (x0,x1) => { x0.strokeStyle = x1 },
      _1926: (x0,x1) => { x0.fillStyle = x1 },
      _1938: (x0,x1) => { x0.lineWidth = x1 },
      _1940: (x0,x1) => { x0.lineCap = x1 },
      _1942: (x0,x1) => { x0.lineJoin = x1 },
      _1948: (x0,x1) => { x0.font = x1 },
      _1950: (x0,x1) => { x0.textAlign = x1 },
      _1952: (x0,x1) => { x0.textBaseline = x1 },
      _1968: x0 => x0.width,
      _2275: x0 => x0.dataTransfer,
      _2279: () => globalThis.window,
      _2322: x0 => x0.location,
      _2341: x0 => x0.navigator,
      _2357: x0 => x0.devicePixelRatio,
      _2600: x0 => x0.performance,
      _2605: x0 => x0.localStorage,
      _2610: x0 => x0.href,
      _2625: x0 => x0.hash,
      _2727: x0 => x0.userAgent,
      _2760: x0 => x0.width,
      _2761: x0 => x0.height,
      _3919: x0 => x0.name,
      _4260: x0 => x0.destination,
      _4262: x0 => x0.currentTime,
      _4391: (x0,x1) => { x0.buffer = x1 },
      _4395: (x0,x1) => { x0.loop = x1 },
      _4397: (x0,x1) => { x0.loopStart = x1 },
      _4399: (x0,x1) => { x0.loopEnd = x1 },
      _4504: x0 => x0.gain,
      _4772: x0 => x0.type,
      _4773: x0 => x0.target,
      _4780: x0 => x0.cancelable,
      _4813: x0 => x0.signal,
      _4883: (x0,x1) => { x0.textContent = x1 },
      _4887: () => globalThis.document,
      _4969: x0 => x0.body,
      _5319: x0 => x0.clientTop,
      _5320: x0 => x0.clientLeft,
      _5321: x0 => x0.clientWidth,
      _5322: x0 => x0.clientHeight,
      _5637: x0 => x0.clientX,
      _5638: x0 => x0.clientY,
      _5639: x0 => x0.ctrlKey,
      _5640: x0 => x0.shiftKey,
      _5641: x0 => x0.altKey,
      _5643: x0 => x0.button,
      _5703: x0 => x0.deltaX,
      _5704: x0 => x0.deltaY,
      _5736: x0 => x0.key,
      _5746: x0 => x0.keyCode,
      _5808: x0 => x0.identifier,
      _5812: x0 => x0.clientX,
      _5813: x0 => x0.clientY,
      _5823: x0 => x0.length,
      _5834: x0 => x0.changedTouches,
      _5835: x0 => x0.altKey,
      _5837: x0 => x0.ctrlKey,
      _5838: x0 => x0.shiftKey,
      _6649: x0 => x0.value,
      _6651: x0 => x0.done,
      _7353: x0 => x0.url,
      _7355: x0 => x0.status,
      _7357: x0 => x0.statusText,
      _7358: x0 => x0.headers,
      _7359: x0 => x0.body,
      _9754: (x0,x1) => { x0.cursor = x1 },
      _9764: (x0,x1) => { x0.display = x1 },
      _9826: (x0,x1) => { x0.font = x1 },
      _9928: (x0,x1) => { x0.height = x1 },
      _10145: x0 => x0.outline,
      _10146: (x0,x1) => { x0.outline = x1 },
      _10578: (x0,x1) => { x0.verticalAlign = x1 },
      _10618: (x0,x1) => { x0.width = x1 },
      _10986: x0 => x0.name,
      _11323: x0 => x0.top,
      _11326: x0 => x0.left,
      _11706: () => globalThis.console,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
