// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: Date.now,
      _7: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _8: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _9: () => {
        let stackString = new Error().stack.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _10: () => typeof dartUseDateNowForTicks !== "undefined",
      _11: () => 1000 * performance.now(),
      _12: () => Date.now(),
      _13: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _14: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _30: s => JSON.stringify(s),
      _31: s => printToConsole(s),
      _32: (o, p, r) => o.replaceAll(p, () => r),
      _33: (o, p, r) => o.replace(p, () => r),
      _34: Function.prototype.call.bind(String.prototype.toLowerCase),
      _35: s => s.toUpperCase(),
      _36: s => s.trim(),
      _39: (string, times) => string.repeat(times),
      _40: Function.prototype.call.bind(String.prototype.indexOf),
      _41: (s, p, i) => s.lastIndexOf(p, i),
      _42: (string, token) => string.split(token),
      _43: Object.is,
      _47: (o, c) => o instanceof c,
      _79: x0 => new Array(x0),
      _81: x0 => x0.length,
      _83: (x0,x1) => x0[x1],
      _84: (x0,x1,x2) => { x0[x1] = x2 },
      _88: (x0,x1,x2) => new DataView(x0,x1,x2),
      _90: x0 => new Int8Array(x0),
      _91: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _92: x0 => new Uint8Array(x0),
      _94: x0 => new Uint8ClampedArray(x0),
      _96: x0 => new Int16Array(x0),
      _98: x0 => new Uint16Array(x0),
      _100: x0 => new Int32Array(x0),
      _102: x0 => new Uint32Array(x0),
      _104: x0 => new Float32Array(x0),
      _106: x0 => new Float64Array(x0),
      _113: x0 => x0.random(),
      _116: () => globalThis.Math,
      _129: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _130: (handle) => clearTimeout(handle),
      _133: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _135: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _136: (x0,x1) => x0.exec(x1),
      _137: (x0,x1) => x0.test(x1),
      _138: x0 => x0.pop(),
      _140: o => o === undefined,
      _142: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _145: o => o instanceof RegExp,
      _146: (l, r) => l === r,
      _147: o => o,
      _148: o => o,
      _149: o => o,
      _150: b => !!b,
      _151: o => o.length,
      _153: (o, i) => o[i],
      _154: f => f.dartFunction,
      _155: () => ({}),
      _156: () => [],
      _158: () => globalThis,
      _161: (o, p) => o[p],
      _162: (o, p, v) => o[p] = v,
      _163: (o, m, a) => o[m].apply(o, a),
      _165: o => String(o),
      _166: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _167: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._167(f,arguments.length,x0) }),
      _168: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._168(f,arguments.length,x0,x1) }),
      _169: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _170: o => [o],
      _171: (o0, o1) => [o0, o1],
      _172: (o0, o1, o2) => [o0, o1, o2],
      _173: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _174: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _175: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _176: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _178: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _180: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _184: x0 => new ArrayBuffer(x0),
      _187: x0 => x0.index,
      _189: x0 => x0.flags,
      _190: x0 => x0.multiline,
      _191: x0 => x0.ignoreCase,
      _192: x0 => x0.unicode,
      _193: x0 => x0.dotAll,
      _194: (x0,x1) => { x0.lastIndex = x1 },
      _195: (o, p) => p in o,
      _196: (o, p) => o[p],
      _205: (x0,x1) => x0.createElement(x1),
      _207: (x0,x1) => x0.querySelector(x1),
      _208: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._208(f,arguments.length,x0) }),
      _209: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._209(f,arguments.length,x0) }),
      _210: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _211: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _212: x0 => x0.preventDefault(),
      _217: () => new AbortController(),
      _218: x0 => x0.abort(),
      _219: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _220: (x0,x1) => globalThis.fetch(x0,x1),
      _221: (x0,x1) => x0.get(x1),
      _222: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._222(f,arguments.length,x0,x1,x2) }),
      _223: (x0,x1) => x0.forEach(x1),
      _224: x0 => x0.getReader(),
      _225: x0 => x0.cancel(),
      _226: x0 => x0.read(),
      _227: x0 => x0.load(),
      _228: (x0,x1) => x0.canPlayType(x1),
      _229: (x0,x1) => x0.cloneNode(x1),
      _230: x0 => x0.pause(),
      _231: x0 => x0.play(),
      _232: x0 => x0.createGain(),
      _233: (x0,x1) => x0.connect(x1),
      _234: (x0,x1,x2) => x0.setValueAtTime(x1,x2),
      _235: () => new AudioContext(),
      _236: (x0,x1) => x0.decodeAudioData(x1),
      _238: x0 => x0.createBufferSource(),
      _239: (x0,x1,x2) => x0.start(x1,x2),
      _240: (x0,x1,x2,x3) => x0.start(x1,x2,x3),
      _243: (x0,x1,x2) => ({event_category: x0,event_label: x1,value: x2}),
      _244: x0 => new Blob(x0),
      _245: (x0,x1) => x0.createImageBitmap(x1),
      _246: (x0,x1,x2,x3,x4) => x0.clearRect(x1,x2,x3,x4),
      _247: (x0,x1,x2,x3,x4) => x0.fillRect(x1,x2,x3,x4),
      _248: (x0,x1,x2,x3,x4,x5,x6) => x0.setTransform(x1,x2,x3,x4,x5,x6),
      _250: (x0,x1,x2,x3,x4) => x0.rect(x1,x2,x3,x4),
      _251: x0 => x0.getBoundingClientRect(),
      _252: x0 => x0.focus(),
      _253: (x0,x1) => x0.item(x1),
      _254: (x0,x1,x2) => x0.uniform1i(x1,x2),
      _259: x0 => x0.save(),
      _260: x0 => x0.clip(),
      _261: x0 => x0.restore(),
      _262: (x0,x1) => x0.append(x1),
      _263: x0 => x0.remove(),
      _264: (x0,x1) => x0.measureText(x1),
      _265: x0 => x0.beginPath(),
      _266: (x0,x1,x2,x3) => x0.strokeText(x1,x2,x3),
      _267: (x0,x1,x2,x3) => x0.fillText(x1,x2,x3),
      _268: (x0,x1,x2) => x0.moveTo(x1,x2),
      _269: (x0,x1,x2) => x0.lineTo(x1,x2),
      _274: (x0,x1) => x0.appendChild(x1),
      _277: x0 => x0.closePath(),
      _285: x0 => x0.fill(),
      _286: (x0,x1,x2,x3,x4,x5,x6) => x0.transform(x1,x2,x3,x4,x5,x6),
      _289: (x0,x1,x2) => x0.blendFunc(x1,x2),
      _290: (x0,x1) => x0.blendEquation(x1),
      _292: x0 => x0.createBuffer(),
      _293: (x0,x1,x2) => x0.bindBuffer(x1,x2),
      _294: (x0,x1,x2,x3) => x0.bufferData(x1,x2,x3),
      _295: (x0,x1,x2,x3) => x0.bufferSubData(x1,x2,x3),
      _296: (x0,x1,x2,x3,x4,x5,x6) => x0.vertexAttribPointer(x1,x2,x3,x4,x5,x6),
      _297: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => x0.drawImage(x1,x2,x3,x4,x5,x6,x7,x8,x9),
      _298: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      _299: (x0,x1) => x0.enable(x1),
      _300: (x0,x1) => x0.disable(x1),
      _301: (x0,x1,x2) => x0.pixelStorei(x1,x2),
      _303: (x0,x1,x2) => x0.bindFramebuffer(x1,x2),
      _304: (x0,x1,x2,x3,x4) => x0.viewport(x1,x2,x3,x4),
      _305: (x0,x1,x2,x3,x4) => x0.colorMask(x1,x2,x3,x4),
      _306: (x0,x1,x2,x3,x4) => x0.clearColor(x1,x2,x3,x4),
      _307: (x0,x1) => x0.clear(x1),
      _309: (x0,x1,x2,x3) => x0.stencilFunc(x1,x2,x3),
      _310: (x0,x1) => x0.activeTexture(x1),
      _311: (x0,x1,x2) => x0.bindTexture(x1,x2),
      _314: x0 => x0.createFramebuffer(),
      _315: (x0,x1,x2,x3,x4,x5) => x0.framebufferTexture2D(x1,x2,x3,x4,x5),
      _316: (x0,x1,x2,x3,x4) => x0.framebufferRenderbuffer(x1,x2,x3,x4),
      _317: (x0,x1,x2,x3) => x0.uniformMatrix4fv(x1,x2,x3),
      _318: (x0,x1) => x0.useProgram(x1),
      _319: (x0,x1,x2,x3,x4) => x0.drawElements(x1,x2,x3,x4),
      _320: x0 => x0.createProgram(),
      _321: (x0,x1,x2) => x0.attachShader(x1,x2),
      _322: (x0,x1) => x0.linkProgram(x1),
      _323: (x0,x1,x2) => x0.getProgramParameter(x1,x2),
      _324: x0 => x0.isContextLost(),
      _325: (x0,x1) => x0.getProgramInfoLog(x1),
      _326: (x0,x1) => x0.createShader(x1),
      _327: (x0,x1,x2) => x0.shaderSource(x1,x2),
      _328: (x0,x1) => x0.compileShader(x1),
      _329: (x0,x1,x2) => x0.getShaderParameter(x1,x2),
      _330: (x0,x1) => x0.getShaderInfoLog(x1),
      _331: (x0,x1,x2) => x0.getActiveAttrib(x1,x2),
      _332: (x0,x1,x2) => x0.getAttribLocation(x1,x2),
      _333: (x0,x1) => x0.enableVertexAttribArray(x1),
      _334: (x0,x1,x2) => x0.getActiveUniform(x1,x2),
      _335: (x0,x1,x2) => x0.getUniformLocation(x1,x2),
      _337: (x0,x1,x2,x3,x4) => x0.renderbufferStorage(x1,x2,x3,x4),
      _338: x0 => x0.createRenderbuffer(),
      _339: (x0,x1,x2) => x0.bindRenderbuffer(x1,x2),
      _340: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _341: (x0,x1,x2,x3) => x0.texParameteri(x1,x2,x3),
      _344: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => x0.texImage2D(x1,x2,x3,x4,x5,x6,x7,x8),
      _345: (x0,x1) => x0.isEnabled(x1),
      _346: (x0,x1,x2,x3,x4,x5,x6) => x0.texImage2D(x1,x2,x3,x4,x5,x6),
      _347: x0 => x0.createTexture(),
      _348: x0 => x0.getError(),
      _352: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._352(f,arguments.length,x0) }),
      _353: (x0,x1) => x0.requestAnimationFrame(x1),
      _354: x0 => new TouchEvent(x0),
      _355: x0 => x0.clear(),
      _357: (x0,x1,x2) => x0.setItem(x1,x2),
      _358: (x0,x1) => x0.getItem(x1),
      _359: (x0,x1) => x0.assign(x1),
      _360: (x0,x1) => x0.replace(x1),
      _361: x0 => x0.reload(),
      _362: (x0,x1,x2) => globalThis.gtag(x0,x1,x2),
      _363: (x0,x1) => x0.error(x1),
      _364: x0 => x0.now(),
      _365: (x0,x1,x2,x3) => ({event_category: x0,event_label: x1,value: x2,name: x3}),
      _370: o => o instanceof Array,
      _380: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _381: a => a.length,
      _383: (a, i) => a[i],
      _384: (a, i, v) => a[i] = v,
      _386: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _389: o => o instanceof Uint8Array,
      _390: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _391: o => o instanceof Int8Array,
      _392: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _393: o => o instanceof Uint8ClampedArray,
      _394: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _395: o => o instanceof Uint16Array,
      _396: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _397: o => o instanceof Int16Array,
      _398: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _399: o => o instanceof Uint32Array,
      _400: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _401: o => o instanceof Int32Array,
      _402: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _405: o => o instanceof Float32Array,
      _406: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _407: o => o instanceof Float64Array,
      _408: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _409: (t, s) => t.set(s),
      _411: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _413: o => o.buffer,
      _414: o => o.byteOffset,
      _415: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _416: (b, o) => new DataView(b, o),
      _417: (b, o, l) => new DataView(b, o, l),
      _418: Function.prototype.call.bind(DataView.prototype.getUint8),
      _419: Function.prototype.call.bind(DataView.prototype.setUint8),
      _420: Function.prototype.call.bind(DataView.prototype.getInt8),
      _421: Function.prototype.call.bind(DataView.prototype.setInt8),
      _422: Function.prototype.call.bind(DataView.prototype.getUint16),
      _423: Function.prototype.call.bind(DataView.prototype.setUint16),
      _424: Function.prototype.call.bind(DataView.prototype.getInt16),
      _425: Function.prototype.call.bind(DataView.prototype.setInt16),
      _426: Function.prototype.call.bind(DataView.prototype.getUint32),
      _427: Function.prototype.call.bind(DataView.prototype.setUint32),
      _428: Function.prototype.call.bind(DataView.prototype.getInt32),
      _429: Function.prototype.call.bind(DataView.prototype.setInt32),
      _434: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _435: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _436: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _437: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _438: Function.prototype.call.bind(Number.prototype.toString),
      _439: Function.prototype.call.bind(BigInt.prototype.toString),
      _440: Function.prototype.call.bind(Number.prototype.toString),
      _441: (d, digits) => d.toFixed(digits),
      _447: (x0,x1) => x0.getContext(x1),
      _450: (x0,x1,x2) => x0.getContext(x1,x2),
      _574: x0 => x0.offsetTop,
      _578: x0 => x0.style,
      _780: x0 => x0.tabIndex,
      _781: (x0,x1) => { x0.tabIndex = x1 },
      _1009: x0 => x0.src,
      _1010: (x0,x1) => { x0.src = x1 },
      _1021: x0 => x0.width,
      _1023: x0 => x0.height,
      _1180: x0 => x0.error,
      _1181: x0 => x0.src,
      _1182: (x0,x1) => { x0.src = x1 },
      _1190: (x0,x1) => { x0.preload = x1 },
      _1192: x0 => x0.readyState,
      _1194: x0 => x0.currentTime,
      _1195: (x0,x1) => { x0.currentTime = x1 },
      _1214: (x0,x1) => { x0.volume = x1 },
      _1856: x0 => x0.width,
      _1857: (x0,x1) => { x0.width = x1 },
      _1858: x0 => x0.height,
      _1859: (x0,x1) => { x0.height = x1 },
      _1892: (x0,x1) => { x0.globalAlpha = x1 },
      _1894: (x0,x1) => { x0.globalCompositeOperation = x1 },
      _1900: (x0,x1) => { x0.strokeStyle = x1 },
      _1902: (x0,x1) => { x0.fillStyle = x1 },
      _1914: (x0,x1) => { x0.lineWidth = x1 },
      _1916: (x0,x1) => { x0.lineCap = x1 },
      _1918: (x0,x1) => { x0.lineJoin = x1 },
      _1924: (x0,x1) => { x0.font = x1 },
      _1926: (x0,x1) => { x0.textAlign = x1 },
      _1928: (x0,x1) => { x0.textBaseline = x1 },
      _1944: x0 => x0.width,
      _2251: x0 => x0.dataTransfer,
      _2255: () => globalThis.window,
      _2298: x0 => x0.location,
      _2317: x0 => x0.navigator,
      _2333: x0 => x0.devicePixelRatio,
      _2576: x0 => x0.performance,
      _2581: x0 => x0.localStorage,
      _2586: x0 => x0.href,
      _2601: x0 => x0.hash,
      _2703: x0 => x0.userAgent,
      _2736: x0 => x0.width,
      _2737: x0 => x0.height,
      _3895: x0 => x0.name,
      _4236: x0 => x0.destination,
      _4238: x0 => x0.currentTime,
      _4367: (x0,x1) => { x0.buffer = x1 },
      _4371: (x0,x1) => { x0.loop = x1 },
      _4373: (x0,x1) => { x0.loopStart = x1 },
      _4375: (x0,x1) => { x0.loopEnd = x1 },
      _4480: x0 => x0.gain,
      _4748: x0 => x0.type,
      _4749: x0 => x0.target,
      _4756: x0 => x0.cancelable,
      _4789: x0 => x0.signal,
      _4859: (x0,x1) => { x0.textContent = x1 },
      _4863: () => globalThis.document,
      _4945: x0 => x0.body,
      _5295: x0 => x0.clientTop,
      _5296: x0 => x0.clientLeft,
      _5297: x0 => x0.clientWidth,
      _5298: x0 => x0.clientHeight,
      _5613: x0 => x0.clientX,
      _5614: x0 => x0.clientY,
      _5615: x0 => x0.ctrlKey,
      _5616: x0 => x0.shiftKey,
      _5617: x0 => x0.altKey,
      _5619: x0 => x0.button,
      _5679: x0 => x0.deltaX,
      _5680: x0 => x0.deltaY,
      _5712: x0 => x0.key,
      _5722: x0 => x0.keyCode,
      _5784: x0 => x0.identifier,
      _5788: x0 => x0.clientX,
      _5789: x0 => x0.clientY,
      _5799: x0 => x0.length,
      _5810: x0 => x0.changedTouches,
      _5811: x0 => x0.altKey,
      _5813: x0 => x0.ctrlKey,
      _5814: x0 => x0.shiftKey,
      _6625: x0 => x0.value,
      _6627: x0 => x0.done,
      _7329: x0 => x0.url,
      _7331: x0 => x0.status,
      _7333: x0 => x0.statusText,
      _7334: x0 => x0.headers,
      _7335: x0 => x0.body,
      _9730: (x0,x1) => { x0.cursor = x1 },
      _9740: (x0,x1) => { x0.display = x1 },
      _9802: (x0,x1) => { x0.font = x1 },
      _9904: (x0,x1) => { x0.height = x1 },
      _10121: x0 => x0.outline,
      _10122: (x0,x1) => { x0.outline = x1 },
      _10554: (x0,x1) => { x0.verticalAlign = x1 },
      _10594: (x0,x1) => { x0.width = x1 },
      _10962: x0 => x0.name,
      _11299: x0 => x0.top,
      _11302: x0 => x0.left,
      _11682: () => globalThis.console,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
